name: Default actions

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the tests
        run: ./test